### ISSUE TITLE
Review code base

### ISSUE THREAD

**Issue by Morganamilo** [ably/ably-control-go#9]
It probably makes more sense to have this reviewed after it's in a presentable state rather than on each  commit.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/IAC-33) by [Unito](https://www.unito.io)

**Comment by Morganamilo** [comment]
Code is pretty much finished for now so I think it's time for review. As time of writing the code base is at commit [0506cc7](https://github.com/ably/ably-control-go/commit/0506cc735da58f197f28d46acbc79083b7d2d17f).

As for potential reviewers, would any of you like to review?

@graham-russell @kavalerov @Peter-Maguire @mohyour

**Comment by kavalerov** [comment]
I am not the biggest Go specialist, but happy to review the API from product perspective. Would be good to have someone from engineering side to do a proper review of the code itself.

**Comment by Peter-Maguire** [comment]
I've taken a look and it looks good to me. The minimum go version specified in go.mod could probably be lower, if you're not using any 1.18 features

**Comment by Morganamilo** [comment]
It's just the version of go the code was written against. It's not a minimum version.

**Comment by mohyour** [comment]
This looks great

**Comment by Morganamilo** [comment]
Thanks, closing as I had 2 okays. Future stuff will be done with PR's an actual reviewers.
